### ISSUE TITLE
Support for dmaker.fan.p39?

### ISSUE THREAD

**Issue by Rene1695** [merdok/homebridge-xiaomi-fan#132]
Hey,

i was wondering if there is support for the dmaker.fan.p39 (tower ventilator)? I was able to add it to home bridge via your plugin, but it seems that the functions are kind of buggy. I can switch between four modes but I can't disable the fan via HomeKit. Also there is no status about the fan percentage visible. 

Are you still working on this and add that device in the future? :)

**Comment by Rene1695** [comment]
![image](https://github.com/merdok/homebridge-xiaomi-fan/assets/71972934/50926bc6-b6cb-4da0-b16b-52d2b582960f)

**Comment by merdok** [comment]
Hi, 
this plugin is more or less obsolete for newer devices and I recommend you to use the homebridge-miot plugin. 

Older devices which use the old miio protocol can still use this plugin but I do not plan to add any new fans here anymore, especially because the miot plugin supports automatic device detection and setup.

**Comment by Rene1695** [comment]
Hi,

thank you for the reply! Just tried the miot plugin and its working perfectly fine, thanks for the tip :)

**Comment by Rene1695** [comment]
Hi,

thank you for the reply! Just tried the miot plugin and its working perfectly fine, thanks for the tip :)
