### ISSUE TITLE
Language inconsistencies between MiHome and this plugin

### ISSUE THREAD

**Issue by jsiegenthaler** [merdok/homebridge-xiaomi-fan#19]
Language inconsistencies between MiHome and this plugin

Xiaomi Home: Turn left / Turn right
Plugin: Move left / Move right

Xiaomi: Buzzer
Plugin: Sound

Xiaomi: Light
Plugin: LED

Also Xioami app allows Mode to be Standard or Natural, but never both off. This could be accomplished with one switch: Natural = On/Off. When Natural is Off, the fan is in Standard Mode. When On, then in Natural mode. You could thus save a switch in the UI.

**Comment by merdok** [comment]
I do not see any problem with this minor naming inconsistency. This is not the MiHome app and if you do not like the names then you can just simply rename the switches straight in the home app. 
As for the mode indeed when i think about it, it would make more sense to make it as a single switch instead of two. Currently you cannot have both off or on anyway, but yes making this as a one switch would save ui.

**Comment by merdok** [comment]
As of version 1.1.0 the modeButtons have been renamed to naturalModeButton and is now just one switch!

**Comment by jsiegenthaler** [comment]
Thanks, that's a good solution
