### ISSUE TITLE
Typo in Example configuration: xioamifan

### ISSUE THREAD

**Issue by DJay-X** [merdok/homebridge-xiaomi-fan#2]
@merdok 

There is a typo in your example configuration.
**xioamifan**
"accessory": "xioamifan",

Should be "xiaomifan"

And a quick feedback.
The plugin worked with fan instantly. 
Looks good to my with a quick test. 
Although, the state on/off did not change or very slow. Sometimes the fan did not respond instantly.  When the fan is turned on/off by another remote the status in eve app does not switch to the actual state. Only when manuel refresh.
Never had this problem with the old plugin. 
Many a bit fine tuning? If there is anything I can do to help, please of course let me know.

Battery level is not showing, wich is good I think, because this was a problem with the other Plugin from https://github.com/YinHangCode/homebridge-mi-fan
I think my fan does not support showing battery level at all?
Thanks for your work and sharing. 

```
Aug 11 19:35:58 raspberrypi-3BPlus homebridge[11176]: [2019-8-11 19:35:58] Loaded plugin: homebridge-xiaomi-fan
Aug 11 19:35:58 raspberrypi-3BPlus homebridge[11176]: [2019-8-11 19:35:58] Registering accessory 'homebridge-xiaomi-fan.xiaomifan'
Aug 11 19:35:58 raspberrypi-3BPlus homebridge[11176]: [2019-8-11 19:35:58] [Xiaomi Fan] Initializing xiaomifan accessory...
Aug 11 19:36:00 raspberrypi-3BPlus homebridge[11176]: [2019-8-11 19:36:00] [Xiaomi Fan] Xiaomi Fan - connected to Fan
Aug 11 19:36:00 raspberrypi-3BPlus homebridge[11176]: [2019-8-11 19:36:00] [Xiaomi Fan] MiioDevice {
Aug 11 19:36:00 raspberrypi-3BPlus homebridge[11176]:   model=zhimi.fan.za1,
Aug 11 19:36:00 raspberrypi-3BPlus homebridge[11176]:   types=miio,
Aug 11 19:36:00 raspberrypi-3BPlus homebridge[11176]:   capabilities=
Aug 11 19:36:00 raspberrypi-3BPlus homebridge[11176]: }
```

![Napkin 2 11 08 19, 7 56 26 PM](https://user-images.githubusercontent.com/3874239/62837681-6814d480-bc72-11e9-9556-3ff2abaaf09c.png)

**Comment by merdok** [comment]
You are right! Thanks! I will fix that typo.

I think the response is related to the network. I did not notice any delay on my fan.

About that the status does not update when using a different source to control the fan, this is a know issue for me. I currently did not find a way to make the events work for the with the miio library. This is pretty much required to update the homekit status and also for using home automation. I will try to make it work and as soon as i find a ways then i will update the plugin.

Since the plugin was developed on my Smartmi Fan 2s (zhimi.fan.za4) i did not include battery status ot the temperature and humidity sensor data since those are not included in my fan. I think from one version of the fan Xiaomi dropped those things for some reason and they are not anymore present on the newer devices.

**Comment by DJay-X** [comment]
I think the one I have is the 2nd Gen. zhimi.fan.za1
Battery build in but not showing up a level anywhere. And no Hardware Temp/HS sensor build in the fan.

After a day playing around with your plugin and the fan, everything seems to work smooth.
I will stay with your plugin and appreciate the time you invested and your work.
Thanks again for this. 👍

**Comment by merdok** [comment]
I have no idea why Xiaomi removed the battery percentage. At least that would be useful to know when i need to charge it again...

Good to hear 👍 
Will try to find a way to implement the events so automation and more correct status are working!
