### ISSUE TITLE
After updating to 1.1.1 I have additional unnecessary switches

### ISSUE THREAD

**Issue by CooperCGN** [merdok/homebridge-xiaomi-fan#21]
With the latest update I suddenly had additional buttons for child lock and oscillating show up. Any idea why this is happening? They show up on top of the regular elements. Any way to avoid this?

![8C1E3438-C300-477F-93B4-503AFE68DA23](https://user-images.githubusercontent.com/29116509/87235981-66541380-c3e3-11ea-96f0-bb1864f932fd.png)

![7D5F0F41-AE0E-4595-B9B5-4208850CA523](https://user-images.githubusercontent.com/29116509/87236013-a915eb80-c3e3-11ea-810d-0bb74751bf17.png)

**Comment by merdok** [comment]
This is because I removed the rotation service used to change the fan rotation which this fan obviously does not support. I had previously used that to switch between modes (standard or natural) but since nobody really knew that and it was confusing I removed that and added a dedicated switch. 
Why the home app did this I actually do not not know.

**Comment by merdok** [comment]
I have re-added the rotation direction service so everything should be as before now. With the rotation direction switch you can now change the buzzer volume(loud or quiet).
