### ISSUE TITLE
Temperature & Humidity display option

### ISSUE THREAD

**Issue by pb29** [merdok/homebridge-xiaomi-fan#45]
I got an Mi fan 3 (zhimi.fan.za5) and it has Temperature & Humidity sensor, which i didn't never know before I saw it on Mi Home.
but sadly It seems this plugin doesn't support Temperature and Humidity Display. It's not that big deal for me, but It would be nice this plugin supports them!

**Comment by merdok** [comment]
I plan to add temperature & humidity support for the smartmi fan 3. I already did the necessary preparations for that with the latest big update, i just need to implement all the new ui stuff which display those info. I am just not sure when i will be able to do that (currently busy with two other projects), but i will do it for sure 😄 
BTW, does the Smartmi fan 3 work besides that with the plugin? I added the support for that fan but actually never tried it since nobody had it yet 😓 so you might be the first one trying it out 😃

**Comment by pb29** [comment]
oh that's a good news! hope things are get to the places soon. thank you for your hard work too! major features are works just fine. but display led is just don't work, and rotate right and left are sometime stuck at upside.

**Comment by merdok** [comment]
Oh, rotate right and left are wrong way around?

**Comment by pb29** [comment]
oh no no I think you made them automatically turn off when user touch it.(rotate right&left) but they stuck at turn on sometimes like this beginning part of this video I just captured. 
https://youtu.be/VhHIq114clY If i manually turn it off, it's rotate it self 5 degree one more time.

**Comment by merdok** [comment]
Oh, i get it! yes, those are stateless switches and they should actually turn off automatically after you turn them on. Will have to check that out too!

**Comment by merdok** [comment]
Should be available in version 1.4.0. Can you please test it since i have no access to the Smartmi Fan 3?

**Comment by pb29** [comment]
Hi! I just updated the plugin and my fan keeps reconnected to homebridge.
https://imgur.com/a/HpX7vfb

**Comment by merdok** [comment]
Sorry, this is a bug from my side which I will fix later today.

**Comment by merdok** [comment]
Should be fixed in version 1.4.1

**Comment by pb29** [comment]
It works fine now! But it keep saying battery amount is at low.

**Comment by merdok** [comment]
I have also added battery reporting, can you tell me what battery percentage does the fan report? Also temperature and humidity are working?
Besides that i have also added the Ioniser button control.

**Comment by pb29** [comment]
It says it's on low, 0% and not charging status. But it's on charging though. Humidity and temperature is works fine! ![image](https://user-images.githubusercontent.com/26969207/95000962-71909700-0600-11eb-9ee3-9fad7d6158dc.png)![image](https://user-images.githubusercontent.com/26969207/95000964-76554b00-0600-11eb-881b-58d3a1f5d7e0.png)

**Comment by merdok** [comment]
Thanks for the info. I just had a double check and it seems it only reports if it is running on battery or ac, but not the charging state of the battery. Will check it out!
Good to hear that that temperature and humidity are working!

**Comment by merdok** [comment]
@pb29 in version 1.4.2 I removed the battery service from the smartmi fan 3 since it seems that it does not support battery percentage reporting. 
Could you anyway do some small test for me? I have added a new property in version 1.4.2 `deepDebugLog`.
Could you please set that property to `true` and start homebridge in debug mode. The plugin will now log in the console(terminal) all the properties which are retrieved from the fan every few seconds. Could you paste the properties here, once when the fan is on battery power and once when the fan is on AC power?

**Comment by pb29** [comment]
with AC power
```
04/10/2020, 07:34:03 > [04/10/2020, 07:34:03] [xiaomifan] [Xiaomi Fan 3] Updated properties: 
 {
  "power": true,
  "fan_level": 2,
  "child_lock": false,
  "fan_speed": 36,
  "swing_mode": false,
  "swing_mode_angle": 30,
  "power_off_time": 0,
  "buzzer": false,
  "light": 1,
  "mode": 0,
  "anion": true,
  "relative_humidity": 49,
  "temperature": 24.3,
  "battery_power": false,
  "fan_speed_rpm": 287,
  "ac_power": true,
  "country_code": 0
}
```
with battery power
```
04/10/2020, 07:35:54 > [04/10/2020, 07:35:54] [xiaomifan] [Xiaomi Fan 3] Updated properties: 
 {
  "power": true,
  "fan_level": 2,
  "child_lock": false,
  "fan_speed": 36,
  "swing_mode": false,
  "swing_mode_angle": 30,
  "power_off_time": 0,
  "buzzer": false,
  "light": 1,
  "mode": 0,
  "anion": true,
  "relative_humidity": 49,
  "temperature": 24.3,
  "battery_power": true,
  "fan_speed_rpm": 370,
  "ac_power": false,
  "country_code": 0
}
```

**Comment by merdok** [comment]
Ok, thanks for that! So it only reports if it is connected to AC or if it is running on battery, but there is no battery level indicator...
