### ISSUE TITLE
Previous setup

### ISSUE THREAD

**Issue by nilitokl** [merdok/homebridge-xiaomi-fan#55]
Hello, in previous version I had fan in homekit and can run only to click on tile and also I have in detail view of accessory adjustable speed (like on bulbs) It was great. With this new version I can’t run fan only to click to tile but must to go to accessory and then switch. Also there is switch for child lock, why? Also no adjustable only three switches for speed. Is there any way how to change it back? Thank you.

**Comment by merdok** [comment]
Hi,
what fan do you have?
Since the latest version the plugin adjusts the accessory based on what features your fan supports. I am guessing that you have a Dmaker 1C fan, which does not support fan speed as a slider, it only has 3 predefined fan speed levels which are now shown as a buttons.

**Comment by nilitokl** [comment]
Correct 1C. But in previous version it works and I know 33, 66 and 99%, but it works better, no another buttons. Also child lock is now in accessory detail 2x. 1 as a switch and then bellow. Is please any possibility to install somehow old version to HB? Thank you!

**Comment by merdok** [comment]
You can manually install the old version using npm if you wish.
But you have to understand those changes were necessary in order to not confuse people. The old behavior was a quick "hack" from my side to make work fast. Right now the fan accessory only displays those features which the fan actually supports, so in the case of 1C there are the 3 fan speed level buttons exactly like in the Mi Home app. 
I can have a look if i can do something about the child lock two times, but this is how the Home app displays the accessory.

**Comment by nilitokl** [comment]
Thank you. I would like but if I use: npm i homebridge-xiaomi-fan@1.3.1 do not see plug-in in homebridge. :(

**Comment by merdok** [comment]
you have to specify the -g parameter for global `sudo npm install -g homebridge-xiaomi-fan@1.3.1`

**Comment by nilitokl** [comment]
Thanks a lot! I needed to reset homekit in homebridge but now it works how I need. :)

**Comment by stijndevries** [comment]
I actually also preferred the previous method... would it be possible to add  a setting to use the slider even on fans with 3 options?

**Comment by merdok** [comment]
Possible yes, but honestly like I already mentioned this was just a quick hack from my side in order to make the dmaker 1c work since there was a lot of requests for that fan. I can understand that some people already got used to that, but from a logical perspective that implementation was wrong. The xiaomi home app also does not have a slider for that fan.
I agree with you that the home app kind of displays the fan without the slider strange, not sure why it is happening like that and unfortunately I cannot control that. Also the dmaker 1c is the only fan currently which I know that does not support free speed setting so basically it is the only one affected. 
Why do you think that the slider hack was better then the current implementation? Is it also because of the layout or is there any other reason?

**Comment by stijndevries** [comment]
Siri control mainly. I could ask "set the fan to 30%, 70%, 100%". Thats not possible now. In the home app I can't easily see the speed 
Now when I turn on level 1, then turn on level two, level one stays on. 

I understand that this is better from a technical perspective but from a user experience perspective the are honestly only disadvantages. Rounding a slider to the closest possible value was a fantastic solution IMO. 

With only one possible active state, typically a radio button should be used (not a switch, the Mi home app also uses radio buttons) but those are not available in the Home app.

**Comment by merdok** [comment]
You can still use Siri by simply telling her to turn on the switch with the desired level.

When you turn on level two and level one is still active then this is a bug and should be communicated so. I will check that out.

This not only better from a technical perspective but also from user experience perspective. It is just confusing for new users if a slider is shown with 100 values where only 3 work. Like I mentioned, you just got used to it because I did the hack at the beginning. If I would do the levels from the beginning then I am pretty sure that there would be no issues with that😉 

The fact is that the dmaker 1c does not support free speed level control and that should clearly be shown for all users.

**Comment by olyckne** [comment]
I can't really see how three tiles are better than one for adjusting the speed? That's just way too many tiles cluttering up my screen.
Would love to see an option for this.

Or an easier way to get to the oscillation so I can group all tiles together.

**Comment by merdok** [comment]
Again, the dmaker 1C is a AC fan which lacks some features like free speed control or custom oscillation angle support. This lack of features should be clearly communicated to the user to prevent confusion. Besides that i do not understand how 3 tiles with exact speeds that the fan supports is worse then a fake slider...
A dedicated button to enable/disable oscillation could be definitely possible, but I really do not understand your statement... You would like to have a dedicated button for oscillation but on the other hand you complain about the many tiles that clutter your screen?

**Comment by olyckne** [comment]
> A dedicated button to enable/disable oscillation could be definitely possible, but I really do not understand your statement... You would like to have a dedicated button for oscillation but on the other hand you complain about the many tiles that clutter your screen?

You can group tiles together, it's even the default nowadays. But turning oscillation on/off that way is a pain which means I separate them into their individual tiles. 
Before this update it was three tiles all together (fan, speed, sleep mode), now it's five. With a dedicated button for oscillation I could group them all into one tile and probably be totally fine with tree switches for the fan speed.

Having a hard time seeing this as an improvement:
![image](https://user-images.githubusercontent.com/1079027/97900651-3e464280-1d3b-11eb-9487-1a713245cb65.jpeg)

**Comment by merdok** [comment]
All the tiles for the fan are already grouped in the fan accessory per default, maybe you ungrouped them?
Anyway, you do not have to see it as an improvement, this is what the fan supports. Like already stated, the fan speed was just a quick workaround to make it work as many people requested support for this fan, the fact is that the fan supports 3 fan levels and this is what it reports so i am using this. Since the plugin now supports much more fans then it was intendent to be (at the beginning it was just for my fan 😉). proper support for all the different fans needs to be included in an simple and easy to add new fans way. based on fan capabilities... 

The big issue is here that because of the workaround which i did some people got used to it, but this is just not the way it is suppose to be 😓

**Comment by olyckne** [comment]
> All the tiles for the fan are already grouped in the fan accessory per default, maybe you ungrouped them?

Yes, like I said I ungrouped them because it's way too many steps to get to the oscillation switch otherwise. A dedicated switch for it would help. 

In my opinion though it's a fan where you can change the speed to three different levels so of course it should use the control for changing speed since that's what you're changing. As far as I understand that characteristic even have the ability to specify a min step value that I guess was at least partly implemented to be able to feature this kind of thing.

**Comment by merdok** [comment]
If you do not like the many steps to get to the oscillation then i would recommend you send some feedback to Apple since they have designed this, maybe if enough people send feedback then they will optimize this.
