### ISSUE TITLE
Enable/disable oscillation

### ISSUE THREAD

**Issue by harryslapalot** [merdok/homebridge-xiaomi-fan#69]
It would be nice to have a switch to enable or disable oscillation. It is only possible to select oscillation angles.
Right now I have to select 0 and then move the fan where I want it to point.
It would be easier to just stop oscillation and have a standard value (to be defined in settings) for the oscillation angle.

**Comment by merdok** [comment]
You can just simply press the active oscillation angle button to disable it. Is that not enough?

**Comment by harryslapalot** [comment]
You mean the blue button with the white circle arrow? That does nothing for me. I thought it was just used to change between loud and silent beepers? Is there anything in the configuration that I am missing? Do I need to have oscillation angled configured?

**Comment by merdok** [comment]
First off what fan do you have? You are talking about oscillation angles so i suppose that you have a fan which supports oscillation angles, is that right? If so then you can just simply press the active oscillation angle to disable oscillation completely.

**Comment by harryslapalot** [comment]
I have a Smartmi Standing Fan 2S. Ok I see what you mean. That will work for me. Thanks for your help and the fast reply!

**Comment by merdok** [comment]
I mean this behavior is not documented in the README so i guess i should add for more clarification in the future. Also maybe i will add a dedicated switch to enable/disable oscillation for the people who want that. I currently used the angle buttons for that because i did not want to add more switches to the UI, less is usually better but i am not sure if that works for that case 😄  Anyway there is already an official enable/disable oscillation button on the fan accessory but that i quite hidden so a lot of people miss that...
