### ISSUE TITLE
Problems with Smartmi Fan 3

### ISSUE THREAD

**Issue by InfernoTom** [merdok/homebridge-xiaomi-fan#88]
Hey there,
thanks for your great plugin! I've been using it for a while for a Fan 2S and now I've got the Fan 3 as well. Unfortunately it is not working. My configuration looks like this:
` "name": "Ventilator Büro",
                    "ip": "ip",
                    "token": "token",
                    "deviceId": "id",
                    "model": "zhimi.fan.za5",
                    "pollingInterval": 5,
                    "buzzerControl": false,
                    "ledControl": true,
                    "naturalModeControl": true,
                    "sleepModeControl": false,
                    "moveControl": false,
                    "shutdownTimer": false,
                    "ioniserControl": true,
                    "fanLevelControl": true`

I get this issue which results in a "no answer" in my home kit app:
`[07/06/2021, 13:55:45] [homebridge-xiaomi-fan] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
[07/06/2021, 13:55:46] [xiaomifan] [Ventilator Büro] Connected to Fan zhimi.fan.za5
[07/06/2021, 13:55:49] [homebridge-xiaomi-fan] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.`

**Comment by merdok** [comment]
Hi,

since the Smartmi Fan 3 is a miot device I would recommend that you use my other plugin homebridge-miot for that device. I myself also own that fan and use the miot plugin to control it. 

I check out what is causing the issue in this plugin but nevertheless have a look at the miot plugin which is specially made for the miot devices!

**Comment by InfernoTom** [comment]
Thanks, that worked perfectly! It took some time to synchronize, but now it's all good.

**Comment by merdok** [comment]
Just tested the fan also with this plugin and it also works fine, probably something you entered was not valid?

**Comment by geronimo9005** [comment]
Principally, I am able to use this plugin here to run the Smartmi Fan 3 (actually I am **not** able to get it working with the Mioto Plugin...). However, I am also experiencing problems due to the blue button below the speed control.
When I press this button, the homekit app says "no answer". See screenshots enclosed.

Is there a way to get rid of this blue "rotate" button? (I do not need it.) I was not able to delete it via the plugin parameter settings.
![as far as rotate button not pressed](https://user-images.githubusercontent.com/85544442/121140828-95b11180-c83a-11eb-8a01-a028c2f44675.jpg)
![after rotate button is pressed](https://user-images.githubusercontent.com/85544442/121140825-95187b00-c83a-11eb-888a-9cd898d4c07f.jpg)

**Comment by merdok** [comment]
@geronimo9005 
The miot plugin should work flawlessly, if it does not then ut would be good if you could post a debug log to see what the issue is, I suspect typo in the ip or token.

Also here the "no answer" indicates that an error happened, could you also post a debug log so I can see what exactly happened when you press that button?

**Comment by geronimo9005** [comment]
Thanks for your swift reply. I would really like to help to figure out the problem, but I am only running Hoobs and not the real homebridge and I do not know how to get the debug files. I gave it a try but was not successful.

**Comment by InfernoTom** [comment]
Do you have the chance to enter the console or terminal or connect via ssh? Then enter: "homebridge -D"

**Comment by geronimo9005** [comment]
This is what I get when Miot-Plugin is installed. The whole Hoobs system is then not working anymore.

hoobs@hoobs:~ $ hoobs -d
Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Function.serverListen [as listen] (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/express-ws/lib/index.js:42:40)
    at API.start (/usr/local/lib/node_modules/@hoobs/hoobs/server/api.js:191:17)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/server/cli.js:172:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 80
}
/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs bridge -u /home/hoobs/.hoobs/etc -p /home/hoobs/.hoobs/node_modules -r -d
[HOOBS] Stopping server.
hoobs@hoobs:~ $

**Comment by merdok** [comment]
You first need to shutdown the other HOOBS instance. You are trying to start a new HOOBS instance on the same network address which fails! You can only run one HOOBS at a time on the same network address.

**Comment by geronimo9005** [comment]
Okay, thanks. I have no clue how to do this. I better stop trying to get this working. Sorry for wasting your time. Maybe someone with better skills than I have, can assist in solving this matter.

**Comment by InfernoTom** [comment]
> Okay, thanks. I have no clue how to do this. I better stop trying to get this working. Sorry for wasting your time. Maybe someone with better skills than I have, can assist in solving this matter.

As I'm guessing you're german as me, this maybe helps: [https://smartapfel.de/homebridge/installieren/](https://smartapfel.de/homebridge/installieren/). Reinstall everything and try again. If you need basic help, I may assist you :)

**Comment by merdok** [comment]
It is actually pretty simple, you just need to make sure that you stop HOOBS first before starting a new one. 
Unfortunately this is required for me to have the slightest idea what is happening in your setup, without the log it is just guessing what is going wrong in your setup...

**Comment by merdok** [comment]
@geronimo9005 
About the blue rotate button. I had a look it myself, and actually on the Smartmi Fan 3 it has no usage so that is why when you click on the "no response" message appears. You might then ask why is it visible then... Well, i once actually removed it because i do not like it myself and that changed the layout of the group that much that some people complained about it so i added it back to keep the layout people where used to. 

In the https://github.com/merdok/homebridge-miot plugin the button was never present and unless xiaomi adds such feature i will not add it there.

**Comment by geronimo9005** [comment]
Hi there, thanks for this solution. I got it running with the Miot Plug-in now. Great that you spend so much effort in this.
