### ISSUE TITLE
Couple of problems after adding a Mi Smart Standing Fan 1C

### ISSUE THREAD

**Issue by MrSnoebel** [merdok/homebridge-xiaomi-fan#93]
Adding when just fine, this is my current config:

"name": "My Xiaomi Fan",
                    "ip": "192.168.1.54",
                    "token": "Token is correctly added and working",
                    "deviceId": "239438535",
                    "pollingInterval": 5,
                    "buzzerControl": true,
                    "ledControl": true,
                    "naturalModeControl": false,
                    "sleepModeControl": true,
                    "moveControl": false,
                    "shutdownTimer": false,
                    "ioniserControl": false,
                    "fanLevelControl": true

Everything works, I can control the fan, turn of and on, control the speed with the three switches, childmode works, and also the oscillator function is working.

Fan firmware is 2.0.4.0003
Plugin 1.5.2
Homebridge 1.3.4

But:
1. The tile in homekit shows a orange exclamation mark after several minutes
2. In the main view it says 'No reponse' directly below the name.. but it does works..
3. In the same main view I get 3 big blue butten, both are named 'My Xiaomi fan" but no distiction between them. I learned that one is for on/off, the other is the child mode.. but this is not shown. There is alos no option to remove the child function, as I do not need it and do not like the two buttons.
4. Under those two button it shows a circular arrow, if I push it, it changes shortly to the other direction. But it does not do anything.
5. The oscillator function is very far away in the interface, it is there.. But select main tile => Accessories => Select properties fan => scroll down to the slide button to control it. I hope this can be easier.
6. Status in the tile is weird.. Fan running at low speed.. status is "4 on . 3 off"

**Comment by merdok** [comment]
Hi,
let me try to get to your questions:

1. That means that there was an error, you would need to start homebridge in debug log and check if there is any kind of error happening
2. The same as above, check the homebridge debug log for any errors
3. This is how HomeKit behaves, a group for the fan accessory is created where the main functions are presented. If you do not want that view then you can simply ungroup the fan group and you will get separate tiles for each accessory. You might want to try that out and see if that fits you better.
4. The circular button does nothing on your fan model, it is still kept even on your model because when i remove then the layout gets even more messed up. I once did that and quite some users complained about that so i left it there with no function.
5. This is the same as above, this unfortunately how HomeKit behaves and there is nothing really much that can be done here. As above you can ungroup the to have quicker access to that function.
6. The status is the group cannot also be controlled and is automatically displayed by HomeKit, in the case of a group it usually says how many accessories are active. Again you can ungroup the fan group to have direct access to your accessories and fix that.

Since you have a miot device, i would recommend to use my other plugin for your fan: https://github.com/merdok/homebridge-miot
Generally a lot of things are the same but minor issues from your list does not exists there, like the useless rotation button. 

Anyway it would be good if you could post some debug log so i can at least what your issues with the exclamation mark was, even when you switch to the other plugin.

**Comment by MrSnoebel** [comment]
Thank your the time to look at the issue's. Becoming a big fan of your work !

I switched to miot.

1. The error is gone. If you want I can switch back to xiaomi-fan to look at logs with debug enabled, but for me this plugin works better.
2. I also think related to 1, also solved.
3. No, all different tiles is not better.
4. Circular button is still there, just moved to another place, now on the bottom of the screen.
5. Indeed, same place again.
6. Understood.

New, very annoying issue. The slider for the speed, as this fans has three modes, does not work smoothly.. you need to sometimes select 3 or 4 times before the fan switches to other level. The option using the buttons works fine, but clutters the view dramatically.

**Comment by merdok** [comment]
Thanks!

It would be good if you shortly could switch back to this plugin and at least post the debug log here so in the case that there is an error i can fix it :) Afterwards you can go back to the miot plugin.

3. There is nothing else that can be done here, you also have the option to disable a couple of features which you do not want to reduce the amount of switches, for that see the README what can be disabled/enabled for fans.
4. True, but in miot the circular button serves as a shortcut to quickly enable or disable the oscillation :)
5. You can also use the `swingControl` property in miot to create a dedicated switch to control the oscillation.

The rotation speed is only emulated for the fan since the fan does not actually support steeples fan speed, but it should work smoothly, if you think that it does not work smoothly then it would be nice if you could open an issues in the miot github repo with a homebridge debug log and the property `deepDebugLog` enabled so i can have a look if there is anything which causes delays for you.

**Comment by MrSnoebel** [comment]
No idea why, tried three times now, including the night.. Not able te reproduce the error when debug mode is on.
So I'm sorry, can not provide any logs for you.

I disabled all things I do not need, like led control, mode control and fan level control. Together with the option to use one tile it's now perfect !

It's a very clean interface now:
Can turn on/off the fan with the tile! If you leave the option to use one tile on, that does not work. This was for me one of the things I really missed.   
Indeed, the arrow is still there, but has a function, very nice!
The speed is still a little hard to change, but because you now can set it, and turn on/off fan with tile it's not a big issue.
With the option use as one tile, it's not so easy to turn on or off.
Also nice, because when you deselect all options.. the status is now also very clear.. just showing the speed.

Very very happy with it now!

ps. Do you know what the sleep mode is or does? The manual is not very clear.. If I select the speed looks be increased at some random moments?

**Comment by merdok** [comment]
Good to hear that everything works better now! Maybe with the issues before this was just some one time thing so it does not appear anymore now...
Anyway if you notice anything which is not correct then just let me know!

As for the sleep mode, I do not have any fan with sleep mode so I am not quite sure what it does, but I guess it is meant to be a mode which you run during night when you sleep...
